This is a habit tracker for myself. I notice the feelings of
concentration and satisfaction are similar. And I like these feelings.

Rule is simple: doing it for consecutive 21 days then change the item
from TODO to DONE. Let's see how many DONE I can done.

Any time broken, re-start it from zero. Try to find why I broke on
that day. Is there anything I can do to prevent it happen again? Or
should I change the rule to be more practical or more precise?

* TODO Habit A: no distractive Internet
** rules
*** AA [too hard]
   - no youtube/b*
   - no bbs
   - no blogs

Exceptions are:

   - need to quick solve a programming related questions
   - life emergency
   - planed on agenda

Goal is to focus on the time block that it is supposed to do.

Instead of fully blocking the access to Internet, I try to:
- assign a 20-min section after the morning section to go through
  those distractive webs
- assign a long time block each week at a fix time to do the Internet

*** AB
open computer then check-in to the tasks.

     Let me say it again:

     - Morning, open the Emacs, check in agenda

     - Afternoon, open the Emacs, check in agenda

     - Evening, open the Emacs, check in agenda

Fill the gap with re-file or zk, but don't open the Internet without
any intention.

If during the session find something interesting, make the habit to
capture it. And process it later on.

** logs
*** attempt 4
   <2020-06-19 Fri>
   - [X] Day 01 good day with blocking system on
   - [X] Day 02 good day
   - [X] Day 03 external force to push me on the limit; though some
     distractive Internet they were mostly happen when I cannot do
     something else, e.g., compiling the code. Most of the focusing
     time is on target.
   - [ ] Day 04
   - [ ] Day 05
   - [ ] Day 06
   - [ ] Day 07
   - [ ] Day 08
   - [ ] Day 09
   - [ ] Day 10
   - [ ] Day 11
   - [ ] Day 12
   - [ ] Day 13
   - [ ] Day 14
   - [ ] Day 15
   - [ ] Day 16
   - [ ] Day 17
   - [ ] Day 18
   - [ ] Day 19
   - [ ] Day 20
   - [ ] Day 21

*** attempt 3
<2020-06-14 Sun>
   - [X] Day 01 It's easy. Just checked in when I first opened my
     computer. Try next day, to see if I can open my computer after
     the lunch.
   - [X] Day 02 Not a day start with computer, so cross it.
     Next day, try check it after dinner.
   - [X] Day 03 Not strictly done, but 90% of it. Forget to arrange the
    night tasks.
   - [ ] Day 04 Forget to block the access. I fail check in agenda
     when I open Emacs.

     Lessons learn again: pay attention to the initial cue. It can
     easily destroy the whole section of a day.

     Let me say it again:

     - Morning, open the Emacs, check in agenda

     - Afternoon, open the Emacs, check in agenda

     - Evening, open the Emacs, check in agenda

*** attempt 2
start day: <2020-06-10 Wed>
   - [X] Day 01
   - [X] Day 02
   - [ ] Day 03 end up watch starship this afternoon, and play CS1.6
     in my browser...

*** attempt 1
    start day: <2020-06-05 Fri>
   - [X] Day 01
   - [X] Day 02
   - [X] Day 03 Today, I did browser some of these websites; but I did
         after I finished the task in that block. So, I revise the
         rules. If I can finish this Habit, maybe I can try a more
         restricted Habit tracker challenge.
   - [X] Day 04
   - [ ] Day 05 fail; when check a tech blog, start to read unnecessary
         pages.
** ideas
*** CANCELLED elisp
- write a function:

  For a special task, if check in, after a given time period, using
  bufferfly as a reminder.

  Just use a physical timer.

* TODO Habit B: self reflection
** rules
   review my day in Emacs
   - day
   - week (not yet implement, need to design procedure and test it
     once finished this habit)
** ideas
   BA: review my day in Emacs include every weekly review
** log
start day: <2020-06-05 Fri>
  - [X] Day 01
  - [X] Day 02
  - [X] Day 03
  - [X] Day 04
  - [X] Day 05
  - [X] Day 06
  - [X] Day 07
  - [X] Day 08 I think there's a reason why I am still be able to hold
    Habit B. This habit takes significantly less amount of energy to
    do it. Just one keyboard stroke, then I am in the flow.

    Whereas, H-a, I need to constantly remind myself not doing
    something. And that is hard. It turns out it's more easy to do
    something rather than not to do something.

  - [X] Day 09 H-a is still too hard for me. Let me break it down to
    even more simple action. As the rule-AA write

  - [X] Day 10 when doing cpu, allocate sometime to "ZK" materials
    into my brain

  - [X] Day 11 I don't feel good about open browser during the small
    break. That's where the trouble really comes. Block the access
    again and to see what will happen

  - [X] Day 12 For habit-AB

    Procedure is easy:

    1. After [habit I have], I will [habit I need]
    2. After [habit I need], I will [habit I want]

    After I start my day with [checking in with agenda in the morning], I
    will [checking in with agenda in the afternoon]

    After [checking in with agenda in the afternoon], I will watch
    [youtube] after the work out.

    -- <<THE 2ND LAW: Make It Attractive (90)>>

  - [X] Day 13 I also find my behavior falls into the bad one when I
    somehow need to access INTERNET but my current task is somewhat
    stuck and need to wait some time until I can do something to that
    tasks. This is the critical moment when bad thing is mostly like
    to happen. I think the best way to avoid such thing is to build a
    small tasks pool.

  - [X] Day 14 I find the block system can make little difference.
    Just that little bit effort make today a good day in terms of no
    distractive Internet

  - [X] Day 15 perhaps I can doc more about this journey by moving
    this journal file to ZK? I read the book and this how that book
    influence me. If just letting this log file here, would be a lost.
    Another thing I can see myself over the last several days, was
    that I have the desire to write more. Much more than the time
    prior to ZK.

  - [X] Day 16 yesterday was too busy to file this task. So I did this
    on the next day. Reviewing my Sunday on Monday. I think it's okay
    to this. But, Can I do better? To make the busy day still being
    controlled?

  - [ ] Day 17
  - [ ] Day 18
  - [ ] Day 19
  - [ ] Day 20
  - [ ] Day 21

* TODO Habit C: CPU
** rules
- document progress on CPU
** log
*** attempt 4
   - [ ] Day 01
   - [ ] Day 02
   - [ ] Day 03
   - [ ] Day 04
   - [ ] Day 05
   - [ ] Day 06
   - [ ] Day 07
   - [ ] Day 08
   - [ ] Day 09
   - [ ] Day 10
   - [ ] Day 11
   - [ ] Day 12
   - [ ] Day 13
   - [ ] Day 14
   - [ ] Day 15
   - [ ] Day 16
   - [ ] Day 17
   - [ ] Day 18
   - [ ] Day 19
   - [ ] Day 20
   - [ ] Day 21

*** attempt 3
   - [X] Day 01 around 20m reading. Now with the long article.
   - [ ] Day 02 If I have a busy scheduled day, I think I'd better to
     scale down the work. But do not do nothing. Even just tide the
     notes, plan something to do next day is okay.
*** attempt 2
   - [X] Day 01 https://github.com/randomwangran/CPU/commit/41179ae055ae6f4e3e7cb609027db27d27f51954
   - [X] Day 02 https://github.com/randomwangran/CPU/commit/0db9efa5b2534828e5aeffbc45a52b21284e067b
   - [X] Day 03 https://github.com/randomwangran/CPU/commit/e26365c892b3c8b3a168190147c1984b2c0b436f
   - [X] Day 04 notes no paper
   - [X] Day 05 notes on paper
   - [X] Day 06 notes on paper
   - [X] Day 07 notes on paper
   - [ ] Day 08 the negative side of ZK is that focus on using my
     words to note, I sometime forget the relatively strong routine
     that I already have.
*** attempt 1
 start day <2020-06-04 Thu>
   - [X] Day 01 https://github.com/randomwangran/CPU/commit/391e80fdbbe9f645400b49f71f77fd51bd990710
   - [X] Day 02 https://github.com/randomwangran/CPU/commit/3468cc76296c06c6ded88b9183b3f247dee988c7
   - [X] Day 03 https://github.com/randomwangran/CPU/commit/a81dda0ab83d4ca41c8ef6ecca8cfe4e34cca060
   - [X] Day 04 https://github.com/randomwangran/CPU/commit/7b333ac35637c18513af5add705a5b1c0348fe20
   - [X] Day 05 https://github.com/randomwangran/CPU/commit/bbe474e61be0cce13da614a80de644fd89ec2faf
   - [X] Day 06 https://github.com/randomwangran/CPU/commit/8fb3cf26f629972e1190fbedb7ce0a2096a6b1d2
   - [ ] Day 07 spending the whole night on the plan on guitar
